
# This is training code for the E-Nose ANN differs from the training_data_collection script in that it takes t
# he CSV files generated from the data collection script, and trains a neural network on them. 
# The trained model is then saved as a .pt file which can be loaded for inference in the enose_classifier.py script.
# The code is structured as a GUI application using Tkinter, which allows the user to select the folder containing the training CSV files, 
# and where to save the trained model. It also displays the detected classes and training progress.
# The ENoseDataset class is a custom PyTorch Dataset that loads the training data from the selected folder, 
# and the Model class defines the architecture of the neural network.
import os
import glob
import csv
import tkinter as tk
from tkinter import filedialog, messagebox, ttk
import threading
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, random_split
# Adjust these hyperparameters as needed
EPOCHS        = 50  # Adjust as needed for better performance
BATCH_SIZE    = 64 
LEARNING_RATE = 0.001
# VAlidation split ratio (e.g. 0.8 means 80% train, 20% val)
TRAIN_SPLIT   = 0.8
# Hidden layer size (same for all hidden layers)
HIDDEN_SIZE   = 72
# This class loads the training data from the CSV files generated by the data collection script.
#  It reads all CSV files in the selected folder, extracts the gas name from the filename to create labels, 
# and stores the sensor data and labels as samples for training.
class ENoseDataset(Dataset):
    # The constructor takes a folder path, reads all CSV files in that folder, and processes them to create a list of samples.
    def __init__(self, folder: str):
        self.samples: list[tuple[list[float], int]] = []
        files = glob.glob(os.path.join(folder, "*.csv"))
        if not files:
            raise FileNotFoundError(f"No CSV files found in: {folder}")
        self.classes = sorted({
            os.path.basename(f).split("-")[0].lower() for f in files
        })
    # For each CSV file extract the gas name from the filename to determine the label, read the sensor data, and store it as a sample.
    # All csv files must be named in the formant "gasname-datestamp.csv" for the gas name to be correctly extracted.
    # The sensor data is expected to be in the format of comma-separated values, with each row representing a sample and each column representing a sensor reading.
    # All gases with same name are labeled with the same integer label, which is determined by the index of the gas name in the sorted list of unique gas names.
        for csv_path in files:
            gas_name = os.path.basename(csv_path).split("-")[0].lower()
            label    = self.classes.index(gas_name)
            # Read the CSV file, convert the sensor readings to floats, and store them along with the label in the samples list.
            with open(csv_path, newline="") as f:
                reader     = csv.reader(f)
                header     = next(reader)
                n_features = len(header)

                for row in reader:
                    if len(row) != n_features:
                        continue
                    try:
                        self.samples.append(([float(v) for v in row], label))
                    except ValueError:
                        continue

        self.n_features = len(self.samples[0][0]) if self.samples else 0

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        values, label = self.samples[idx]
        return (
            torch.tensor(values, dtype=torch.float32),
            torch.tensor(label,  dtype=torch.long),
        )
# This class defines the architecture of the neural network used for training. 
# It consists of an input layer, five hidden layers with a specified number of neurons, and an output layer that produces the final classification output.
class Model(nn.Module):
    # The constructor initializes the layers of the neural network. The number of input features, hidden layer size, and number of output classes are all configurable through the parameters.
    def __init__(self, in_features: int, h: int, out_features: int):
        super().__init__()
        self.fc1 = nn.Linear(in_features, h)
        self.fc2 = nn.Linear(h, h)
        self.fc3 = nn.Linear(h, h)
        self.fc4 = nn.Linear(h, h)
        self.fc5 = nn.Linear(h, h)
        self.out = nn.Linear(h, out_features)
    # The forward method defines the forward pass of the neural network. It applies the layers in sequence, using the hyperbolic tangent activation function (tanh) for the hidden layers, and returns the output of the final layer.
    def forward(self, x):
        for layer in (self.fc1, self.fc2, self.fc3, self.fc4, self.fc5):
            x = torch.tanh(layer(x))
        return self.out(x)
# The rest of the code defines the TrainerApp class, which is a
# Tkinter GUI application that allows the user to select the training data folder and save location for the model, and then trains the neural network in a background thread while updating the GUI with progress and logs.
class TrainerApp(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("E-Nose ANN Trainer")
        self.resizable(False, False)
        self._folder_path = None
        self._save_path   = None
        self._build_ui()
    # 
    def _build_ui(self):
        pad = {"padx": 10, "pady": 5}

        tk.Label(self, text="Training CSV folder:").grid(
            row=0, column=0, sticky="w", **pad)
        self.folder_var = tk.StringVar(value="No folder selected")
        tk.Label(self, textvariable=self.folder_var, relief="sunken",
                 width=48, anchor="w").grid(row=0, column=1, **pad)
        tk.Button(self, text="Browse…", command=self._pick_folder).grid(
            row=0, column=2, **pad)

        tk.Label(self, text="Save model to:").grid(
            row=1, column=0, sticky="w", **pad)
        self.save_var = tk.StringVar(value="No location selected")
        tk.Label(self, textvariable=self.save_var, relief="sunken",
                 width=48, anchor="w").grid(row=1, column=1, **pad)
        tk.Button(self, text="Browse…", command=self._pick_save).grid(
            row=1, column=2, **pad)


        tk.Label(self, text="Detected classes:").grid(
            row=2, column=0, sticky="nw", **pad)
        self.classes_text = tk.Text(self, height=5, width=48, state="disabled",
                                    relief="sunken")
        self.classes_text.grid(row=2, column=1, **pad)


        self.progress = ttk.Progressbar(self, length=420, maximum=EPOCHS)
        self.progress.grid(row=3, column=0, columnspan=3, **pad)


        self.log = tk.Text(self, height=14, width=62, state="disabled",
                           bg="#1e1e1e", fg="#d4d4d4", font=("Courier", 9))
        self.log.grid(row=4, column=0, columnspan=3, padx=10, pady=5)

   
        self.train_btn = tk.Button(
            self, text="Start Training", bg="#2d6a4f", fg="white",
            font=("Arial", 11, "bold"), command=self._start_training,
            state="disabled"
        )
        self.train_btn.grid(row=5, column=0, columnspan=3, pady=10)
    # Open a file dialog to select the folder containing the training CSV files,
    #  and then preview the detected classes and number of samples for each class in the GUI.
    def _pick_folder(self):
        folder = filedialog.askdirectory(title="Select folder containing training CSVs")
        if not folder:
            return

        self._folder_path = folder
        self.folder_var.set(folder)

        # Preview classes right away
        try:
            files = glob.glob(os.path.join(folder, "*.csv"))
            if not files:
                raise FileNotFoundError("No CSV files found in that folder.")

            classes = sorted({
                os.path.basename(f).split("-")[0].lower() for f in files
            })

            # Count rows per class (minus header)
            counts = {c: 0 for c in classes}
            for f in files:
                name = os.path.basename(f).split("-")[0].lower()
                with open(f, newline="") as fh:
                    counts[name] += max(0, sum(1 for _ in fh) - 1)

            self.classes_text.config(state="normal")
            self.classes_text.delete("1.0", "end")
            for i, c in enumerate(classes):
                self.classes_text.insert("end",
                    f"  [{i}]  {c:<22}  ({counts[c]:,} rows)\n")
            self.classes_text.config(state="disabled")

            self._check_ready()

        except Exception as e:
            messagebox.showerror("Error scanning folder", str(e))


    # Save dialog to pick where to save the trained model .pt file
    def _pick_save(self):
        path = filedialog.asksaveasfilename(
            title="Save trained model as…",
            defaultextension=".pt",
            filetypes=[("PyTorch model", "*.pt"), ("All files", "*.*")],
            initialfile="enose_ann_model.pt",
        )
        if path:
            self._save_path = path
            self.save_var.set(path)
            self._check_ready()

    def _check_ready(self):
        if self._folder_path and self._save_path:
            self.train_btn.config(state="normal")

    # Helper method to log messages to the GUI log text box from any thread
    def _log(self, msg: str):
        self.after(0, self._append_log, msg)

    def _append_log(self, msg: str):
        self.log.config(state="normal")
        self.log.insert("end", msg + "\n")
        self.log.see("end")
        self.log.config(state="disabled")

    def _set_progress(self, value: int):
        self.after(0, lambda: self.progress.config(value=value))
    # This method is called when the user clicks the "Start Training" button. 
    # It disables the button, resets the log and progress bar, and starts the training process in a background thread to keep the GUI 
    # responsive.
    def _start_training(self):
        self.train_btn.config(state="disabled", text="Training…")
        self.log.config(state="normal")
        self.log.delete("1.0", "end")
        self.log.config(state="disabled")
        self.progress["value"] = 0
        threading.Thread(target=self._run_training, daemon=True).start()
    # This method contains the main training loop. 
    # It loads the dataset, splits it into training and validation sets, initializes the model, criterion, and optimizer, 
    # and then runs the training and validation passes for a specified number of epochs.
    #  It logs the progress and saves the best model based on validation accuracy.
    def _run_training(self):
        try:    
            # 
            self._log("Loading dataset…")
            dataset = ENoseDataset(self._folder_path)

            self._log(f"  Sensors  (features) : {dataset.n_features}")
            self._log(f"  Classes             : {dataset.classes}")
            self._log(f"  Total samples       : {len(dataset):,}")
            self._log(f"  Train / Val split   : {TRAIN_SPLIT*100:.0f}% / {(1-TRAIN_SPLIT)*100:.0f}%")
            # Split dataset into training and validation sets, and create DataLoaders for each.
            n_train = int(len(dataset) * TRAIN_SPLIT)
            n_val   = len(dataset) - n_train
            train_ds, val_ds = random_split(dataset, [n_train, n_val])
            # The DataLoader will handle batching and shuffling of the training data, and batching of the validation data.
            train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
            val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE)
            # Initialize the neural network model, loss criterion, and optimizer. 
            # The model architecture is defined by the Model class, and the number of input features and output classes are determined from the dataset.
            model     = Model(dataset.n_features, HIDDEN_SIZE, len(dataset.classes))
            criterion = nn.CrossEntropyLoss()
            optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)

            self._log(f"\nStarting training — {EPOCHS} epochs")
            self._log("─" * 50)

            best_val_acc = 0.0
            # Main training loop that runs for the specified number of epochs.
            #  In each epoch, it performs a training pass over the training data and a validation pass over the validation data,
            #  logging the average loss and validation accuracy.
            for epoch in range(1, EPOCHS + 1):

                # train pass
                model.train()
                running_loss = 0.0
                for X, y in train_loader:
                    optimizer.zero_grad()
                    loss = criterion(model(X), y)
                    loss.backward()
                    optimizer.step()
                    running_loss += loss.item() * len(X)

                avg_loss = running_loss / n_train

                # validation pass
                model.eval()
                correct = 0
                with torch.no_grad():
                    for X, y in val_loader:
                        correct += (model(X).argmax(1) == y).sum().item()

                val_acc = correct / n_val * 100
                self._set_progress(epoch)

                if epoch % 10 == 0 or epoch == 1:
                    self._log(
                        f"Epoch {epoch:4d}/{EPOCHS}  |  "
                        f"loss: {avg_loss:.4f}  |  val acc: {val_acc:.1f}%"
                    )
                if val_acc > best_val_acc:
                    best_val_acc = val_acc
                    torch.save({'model_state_dict': model.state_dict(), 'classes': dataset.classes, 'n_features': dataset.n_features}, self._save_path)
            self._log("\n" + "─" * 50)
            self._log(f"Training complete!")
            self._log(f"Best validation accuracy : {best_val_acc:.1f}%")
            self._log(f"Model saved to           : {self._save_path}")
            self._log("\nClass index map (for inference script):")
            for i, name in enumerate(dataset.classes):
                self._log(f"  {i}  →  {name}")
            self.after(0, lambda: messagebox.showinfo(
                "Done!",
                f"Training complete.\n\n"
                f"Best val accuracy: {best_val_acc:.1f}%\n"
                f"Model saved to:\n{self._save_path}"
            ))
        except Exception as e:
            self._log(f"\nERROR: {e}")
            self.after(0, lambda: messagebox.showerror("Training failed", str(e)))
        finally:
            self.after(0, lambda: self.train_btn.config(
                state="normal", text="Start Training"))
if __name__ == "__main__":
    app = TrainerApp()
    app.mainloop()